export const STRINGS = {
  HEADER: {
    back: 'Back',
  },
  MODAL: {
    title: 'Introducing Cryptopedia',
    desc: 'Read our launch press release below!',
    readMore: 'Read More',
    other: 'Other Sponsors',
    cancel: 'Cancel',
  },
  DETAIL: {
    cap: 'Market Cap',
    volume: 'Volume',
    change: 'Past 24 hours',
    addToPortfolio: 'Add to porfolio',
    news: 'News',
    more: 'MORE',
    more_news: 'NEWS',
    about: 'About',
    whitepaper: 'READ THE WHITEPAPER',
    creator: 'Creator',
    website: 'Website',
    consensus: 'Consensus Method',
    hash: 'Hashing Algorithm',
    explorer: 'Explorer',
    more_info: 'More Info',
    networks: 'Networks',
  },
  HOME: {
    title: 'Home',
    tapToLearn: 'Tap to start learning about crypto',
    change: 'Change',
    change24H: '24H Change',
    news: 'News',
    sponsor:
      'Tap to read the Cryptopedia launch press release! is our sponsor for the month of September.',
  },
  LEARN: {
    title: 'Learn',
    getStarted: 'Get Started',
    moreCourses: 'More Courses',
    education: 'Corporate education?',
    titleEducation: 'Everything you need to begin your jounery into crypto',
    search: 'Search...',
  },
  MARKETS: {
    title: 'Markets',
  },
  PORTFOLIO: {
    title: 'Portfolio',
  },
  SETTINGS: {
    notifications: 'NOTIFICATIONS',
    toggle: 'Push Notifications',
    settings: 'SETTINGS',
    title: 'Settings',
  },
  ALL_COINS: {
    index: '#',
    name: 'NAME',
    price: 'PRICE',
    change: 'CHANGE',
    cap: 'M.CAP',
  },
};
