export const STRINGS = {
  HEADER: {
    back: 'Back',
    cancel: 'Cancel',
  },
  MODAL: {
    title: 'Introducing Cryptopedia',
    desc: 'Read our launch press release below!',
    readMore: 'Read More',
    other: 'Other Sponsors',
    cancel: 'Cancel',
  },
  DETAIL: {
    cap: 'Market Cap',
    volume: 'Volume',
    change: 'Past 24 hours',
    addToPortfolio: 'Add to porfolio',
    news: 'News',
    more: 'MORE',
    more_news: 'NEWS',
    about: 'About',
    whitepaper: 'READ THE WHITEPAPER',
    creator: 'Creator',
    website: 'Website',
    consensus: 'Consensus Method',
    hash: 'Hashing Algorithm',
    explorer: 'Explorer',
    more_info: 'More Info',
    networks: 'Networks',
  },
  HOME: {
    title: 'Home',
    tapToLearn: 'Tap to start learning about crypto',
    change: 'Change',
    change24H: '24H Change',
    news: 'News',
    sponsor:
      ' is our sponsor for the month of ',
  },
  LEARN: {
    title: 'Learn',
    getStarted: 'Get Started',
    moreCourses: 'More Courses',
    education: 'Corporate education?',
    titleEducation: 'Everything you need to begin your jounery into crypto',
    search: 'Search...',
  },
  MARKETS: {
    title: 'Markets',
    noFav: 'No Favorites.',
    addFav: 'Add it from Market Detail Screen.',
    transactionDesc:
      'Input the amount of tokens you hold and the price your purchased it at.',
    buy: 'Buy',
    sell: 'Sell',
    addTransaction: 'Add transaction',
    price: 'Price (per coin) $',
    number: 'Number of Coins',
    total: 'Total ($)',
    unhandled: 'Unhandled operation',
    notEnough: 'Not enough coins to proceed operation',
    searchPlaceholder: 'Search Coin name or Symbol...',
    currency: 'Select Currency',
    cancel: 'Cancel'
  },
  DEFI: {
    what: 'What is DeFi?',
    invest: 'Invest in DeFi',
    total: 'Total value Locked',
    currency: 'USD',
    topRates: 'Top Rates',
    topPools: 'Top Pools',
    rates: 'All Rates',
    pools: 'All Pools',
    seeAll: 'See All',
    value: ' % APR',
  },
  PORTFOLIO: {
    title: 'Portfolio',
    coin: 'Coin',
    price: 'Price',
    total: 'Total',
    track: 'Track your crypto portfolio here.',
    addCoins: 'Add coins to your portfolio by clicking on a coin in markets.',
  },
  SETTINGS: {
    notifications: 'NOTIFICATIONS',
    toggle: 'Push Notifications',
    settings: 'SETTINGS',
    title: 'Settings',
  },
  ALL_COINS: {
    index: '#',
    name: 'NAME',
    price: 'PRICE',
    change: 'CHANGE',
    cap: 'M.CAP',
  },
};
